# welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarray = np.array([3,6,32,7])

In [3]:
myarray

array([ 3,  6, 32,  7])

# Array creation:conversion fom other python structures

In [4]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [5]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [6]:
listarray.dtype

dtype('int32')

In [7]:
listarray.shape

(3, 3)

In [8]:
listarray.size

9

In [9]:
zeros = np.zeros((2,5))

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
rng = np.arange(15)

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace = np.linspace(1,5,8)

In [14]:
lspace

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [15]:
emp = np.empty((4,6))

In [16]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061414e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 1.29060531e-306,
        2.13620807e-306, 1.69118787e-306, 2.56765117e-312]])

In [17]:
emp_like = np.empty_like(lspace)

In [18]:
emp_like

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [19]:
ide = np.identity(45)

In [20]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [21]:
ide.shape

(45, 45)

In [22]:
arr = np.arange(99)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [24]:
arr = arr.reshape(3,33)

In [25]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
arr = arr.ravel()

In [27]:
arr.shape

(99,)

# numpy axis 1d = [axis0] 2d array = [axis0,axis1]

In [28]:
#in one dimensoanl array on axis 0 is there

In [29]:
x = [[1,2,3,],[4,5,6],[7,8,9]]

In [30]:
ar = np.array(x)

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
ar.sum(axis = 0)

array([12, 15, 18])

In [33]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [34]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [35]:
#T = transpose

In [36]:
ar.flat

In [37]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [38]:
ar.ndim

2

In [39]:
ar.size

9

In [40]:
ar.nbytes

36

In [41]:
one = np.array([1,3,44,634,2])

In [42]:
one.argmax()#this is a method, it gives index of maximum element

3

In [43]:
one.argmin()

0

In [44]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [47]:
ar.argmin()

0

In [48]:
ar.max()

9

In [49]:
ar.argmax(axis = 0)

array([2, 2, 2], dtype=int64)

In [50]:
ar.argmax(axis = 1)

array([2, 2, 2], dtype=int64)

In [51]:
ar.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [52]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
ar.reshape((9))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
ar2 = np.array([[1, 4, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [56]:
ar  +ar2

array([[ 2,  6,  4],
       [ 8,  5, 12],
       [15,  9,  9]])

In [57]:
ar*ar2

array([[ 1,  8,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [58]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [59]:
ar.max()

9

In [60]:
ar.min()

1

In [61]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.count_nonzero(ar)

9

In [64]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [65]:
np.nonzero(ar2)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1], dtype=int64))

In [66]:
ar[1,2]=0

In [67]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [68]:
import sys

In [69]:
py_ar = [0,4,55,2]

In [70]:
np_ar = np.array(py_ar)

In [71]:
sys.getsizeof(1)*len(py_ar)

112

In [72]:
np_ar.itemsize * np_ar.size

16

In [73]:
#numpy array and attributes

In [74]:
np_ar.tolist()

[0, 4, 55, 2]